osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
    - os: osx
cache:
  directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - yarn
script:
  - yarn run build:darwin
branches:
  only:
    - master
